version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "my_postgres"
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
      - my_dbbackup:/backups
volumes:
  my_dbdata:
  my_dbbackup: